public	enum	LayerEnum{
	layer_Default =0,
	layer_TransparentFX,
	layer_IgnoreRaycast,
	layer_BuiltinLayer3,
	layer_Water,
	layer_BuiltinLayer5,
	layer_BuiltinLayer6,
	layer_BuiltinLayer7,
	layer_Debug,
	layer_Player,
	layer_Enemy_Capsule,
	layer_Cutter,
	layer_Attack,
	layer_Stage,
	layer_Chopped,
	layer_Enemy_HitArea,
	layer_CutBox,
	layer_Player_HitArea,
	layer_DummyBox,
	layer_Gimmick,
	layer_ThroughStage,
	layer_Weapon,
	layer_DamageArea,
	layer_Item
};