public	enum	LayerEnum{
	layer_Default =0,
	layer_TransparentFX,
	layer_IgnoreRaycast,
	layer_BuiltinLayer3,
	layer_Water,
	layer_BuiltinLayer5,
	layer_BuiltinLayer6,
	layer_BuiltinLayer7,
	layer_OrigamiCut,
	layer_OrigamiWait,
	layer_OrigamiUpdate,
	layer_LeapHand,
	layer_Effect,
	layer_OrigamiCamera,
};